from .comparisons import within_margin
from .dimensions import average_dimensions
from .dimensions import average_width
from .dimensions import average_height
from .dimensions import y_axis_center
from .dimensions import x_axis_center
from .dimensions import center_point
from .dimensions import center_points
from .representation import simplify_characters
from .selectors import extract_characters_from_pages